import { DefaultStateEnum } from './DefaultStateEnum';

@Component
export struct DefaultStatePage {
  //控制空数据布局和异常布局时是否可以下拉刷新（前提是外部有下拉刷新组件）
  @Prop isEnablePull: boolean = false
  //如果可以下拉刷新,则scroller要外部传入
  scroller?: Scroller = new Scroller()
  @BuilderParam normalPage: () => void;
  @Prop defaultState: number = DefaultStateEnum.LOADING
  @Prop noDataMsg: string
  @Prop errorMsg: string
  icon?: ResourceStr = $r('app.media.common_no_data_icon')
  onRetryCallback?: () => void

  build() {
    if (this.isEnablePull) {
      Scroll(this.scroller) {
        Column() {
          if (this.defaultState === DefaultStateEnum.LOADING) {
            this.loading()
          } else if (this.defaultState === DefaultStateEnum.EMPTY) {
            this.empty()
          } else if (this.defaultState === DefaultStateEnum.ERROR) {
            this.error()
          } else {
            this.normalPage()
          }
        }
        .width('100%')
        .layoutWeight(1)

      }.width('100%')
      .height('100%')
    } else {
      Column() {
        if (this.defaultState === DefaultStateEnum.LOADING) {
          this.loading()
        } else if (this.defaultState === DefaultStateEnum.EMPTY) {
          this.empty()
        } else if (this.defaultState === DefaultStateEnum.ERROR) {
          this.error()
        } else {
          this.normalPage()
        }
      }
      .width('100%')
      .height('100%')

    }


  }

  @Builder
  loading() {
    Column() {
      LoadingProgress()
        .color($r('app.color.theme_color'))
        .height(100)
        .width(100)
        .backgroundColor(Color.Transparent)
    }
    .justifyContent(FlexAlign.Center)
    .width('100%')
    .height('100%')
  }

  @Builder
  empty() {
    Column() {
      Image(this.icon)
        .width(80)
        .height(80)
      Text(this.noDataMsg ? this.noDataMsg : '没有数据').margin({ top: 15 })
    }
    .justifyContent(FlexAlign.Center)
    .width('100%')
    .height('100%')
  }

  @Builder
  error() {
    Column() {
      Image(this.icon)
        .width(80)
        .height(80)
        .onClick(() => {
          this.onRetryCallback?.()
        })
      Text(this.errorMsg ? this.errorMsg : '数据错误').margin({ top: 15 })
        .onClick(() => {
          this.onRetryCallback?.()
        })
    }
    .justifyContent(FlexAlign.Center)
    .width('100%')
    .height('100%')
  }
}