export class PageRouter {
  //Dialog
  static PAGE_POPUP_DIALOG: string = 'page/popup_dialog'
  static PAGE_BIND_SHEET: string = 'page/bind_sheet'
  //Web
  static PAGE_WEB: string = 'page/web'
  static PAGE_WEB_HANDLE: string = 'page/web_handle'
  static PAGE_WEB_ERROR: string = 'page/web_error'
  static PAGE_WEB_NESTED_SCROLL: string = 'page/web_nested_scroll'
  static PAGE_WEB_HANDLE_SCROLL: string = 'page/web_handle_scroll'
  static PAGE_WEB_KEYBOARD: string = 'page/web_keyboard'
  static PAGE_WEB_SHOW_WINDOW: string = 'page/web_show_window'
  static PAGE_WEB_PAGE_LOAD: string = 'page/web_page_load'
  static PAGE_WEB_UPLOAD: string = 'page/web_upload'
  static PAGE_WEB_DOWNLOAD: string = 'page/web_download'
  static PAGE_WEB_MEDIA: string = 'page/web_media'
  static PAGE_COLUMN: string = 'page/column'
  static PAGE_ROW: string = 'page/row'
  static PAGE_STACK: string = 'page/stack'
  static PAGE_FLEX: string = 'page/flex'
  static PAGE_SCROLL: string = 'page/scroll'
  static PAGE_RELATIVE_CONTAINER:string='page/RelativeContainer'
}