/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { common } from '@kit.AbilityKit';
import { preferences } from '@kit.ArkData';
import { BusinessError } from '@kit.BasicServicesKit';
import { util } from '@kit.ArkTS';

const PREFERENCES_NAME: string = 'zhq_preference';

export class PreferenceManager {
  private preferences?: preferences.Preferences;
  private context = getContext(this) as common.UIAbilityContext;
  private static instance: PreferenceManager;

  constructor() {
    this.initPreference(PREFERENCES_NAME);
  }

  public static getInstance(): PreferenceManager {
    if (!PreferenceManager.instance) {
      PreferenceManager.instance = new PreferenceManager();
    }
    return PreferenceManager.instance;
  }

  async initPreference(storeName: string): Promise<void> {
    let options: preferences.Options = { name: storeName }
    //Api 18以上
    // if (preferences.isStorageTypeSupported(preferences.StorageType.GSKV)) {
    //   options.storageType = preferences.StorageType.GSKV
    // } else {
    //   options.storageType = preferences.StorageType.XML
    // }
    return preferences.getPreferences(this.context, options)
      .then((preferences: preferences.Preferences) => {
        this.preferences = preferences;
      }).catch((error: BusinessError) => {
        console.error('---initPreference Error:' + JSON.stringify(error))
      })
  }

  async setValue<T>(key: string, value: T): Promise<void> {
    if (this.preferences) {
      // 当字符串有特殊字符时，需要将字符串转为Uint8Array类型再存储，长度均不超过16 * 1024 * 1024个字节。
      // let uInt8Array1 = new util.TextEncoder().encodeInto("~！@#￥%……&*（）——+？");
      this.preferences.put(key, JSON.stringify(value)).then(() => {
        this.saveUserData();
      })
    } else {
      this.initPreference(PREFERENCES_NAME).then(() => {
        this.setValue<T>(key, value);
      });
    }
  }

  async getValue<T>(key: string): Promise<T | null> {
    if (this.preferences) {
      // 当获取的值为带有特殊字符的字符串时，需要将获取到的Uint8Array转换为字符串
      // let uInt8Array2 : preferences.ValueType = dataPreferences.getSync('uInt8', new Uint8Array(0));
      // let textDecoder = util.TextDecoder.create('utf-8');
      // val = textDecoder.decodeToString(uInt8Array2 as Uint8Array);
      return this.preferences.get(key, '').then((res: preferences.ValueType) => {
        let value: T | null = null;
        if (res) {
          value = JSON.parse(res as string) as T;
        }
        return value;
      });
    } else {
      return this.initPreference(PREFERENCES_NAME).then(() => {
        return this.getValue<T>(key);
      });
    }
  }

  async hasValue(key: string): Promise<boolean> {
    if (this.preferences) {
      return this.preferences.has(key);
    } else {
      return this.initPreference(PREFERENCES_NAME).then(() => {
        return this.hasValue(key);
      });
    }
  }

  async deleteValue(key: string): Promise<void> {
    if (this.preferences) {
      this.preferences.delete(key).then(() => {
        this.saveUserData();
      });
    } else {
      this.initPreference(PREFERENCES_NAME).then(() => {
        this.deleteValue(key);
      });
    }
  }

  saveUserData() {
    this.preferences?.flush();
  }

  clear(){
    if (this.preferences) {
      this.preferences.clear(()=>{

      })
    }else {
      this.initPreference(PREFERENCES_NAME).then(()=>{
        this.clear()
      })
    }
  }

  onChangedRegister(){
    if (this.preferences){
      this.preferences?.on('change',(value)=>{
        console.debug('===Key：'+value+' Changed')
      })
    }

  }

  onChangedUnregister(){
    if (this.preferences) {
      this.preferences.off('change',(value)=>{

      })
    }
  }
}