import { access, ble } from '@kit.ConnectivityKit'
import { PermissionUtils, ToastUtils } from '@ohos/common'
import { common, Permissions } from '@kit.AbilityKit'


const BLE_ADV_TYPE_FLAG = 0x01;
const BLE_ADV_TYPE_16_BIT_SERVICE_UUIDS_INCOMPLETE = 0x02;
const BLE_ADV_TYPE_16_BIT_SERVICE_UUIDS_COMPLETE = 0x03;
const BLE_ADV_TYPE_32_BIT_SERVICE_UUIDS_INCOMPLETE = 0x04;
const BLE_ADV_TYPE_32_BIT_SERVICE_UUIDS_COMPLETE = 0x05;
const BLE_ADV_TYPE_128_BIT_SERVICE_UUIDS_INCOMPLETE = 0x06;
const BLE_ADV_TYPE_128_BIT_SERVICE_UUIDS_COMPLETE = 0x07;
const BLE_ADV_TYPE_LOCAL_NAME_SHORT = 0x08;
const BLE_ADV_TYPE_LOCAL_NAME_COMPLETE = 0x09;
const BLE_ADV_TYPE_TX_POWER_LEVEL = 0x0A;
const BLE_ADV_TYPE_16_BIT_SERVICE_SOLICITATION_UUIDS = 0x14;
const BLE_ADV_TYPE_128_BIT_SERVICE_SOLICITATION_UUIDS = 0x15;
const BLE_ADV_TYPE_32_BIT_SERVICE_SOLICITATION_UUIDS = 0x1F;
const BLE_ADV_TYPE_16_BIT_SERVICE_DATA = 0x16;
const BLE_ADV_TYPE_32_BIT_SERVICE_DATA = 0x20;
const BLE_ADV_TYPE_128_BIT_SERVICE_DATA = 0x21;
const BLE_ADV_TYPE_MANUFACTURER_SPECIFIC_DATA = 0xFF;

const BLUETOOTH_UUID_16_BIT_LENGTH = 2;
const BLUETOOTH_UUID_32_BIT_LENGTH = 4;
const BLUETOOTH_UUID_128_BIT_LENGTH = 16;

const BLUETOOTH_MANUFACTURE_ID_LENGTH = 2;

@Entry
@Component
struct BlueToothTestPage {
  @State bluetoothStateStr: string = '蓝牙状态'
  @State bluetoothState: access.BluetoothState = access.BluetoothState.STATE_OFF
  private context = getContext(this) as common.UIAbilityContext
  @State bluetoothDeviceList: Array<string> = []
  private listScroller: Scroller = new Scroller()

  aboutToAppear(): void {
    access.on("stateChange", (state: access.BluetoothState) => {
      this.bluetoothState = state
      switch (state) {
        case access.BluetoothState.STATE_TURNING_ON:
          this.bluetoothStateStr = '蓝牙状态：STATE_TURNING_ON'
          break
        case access.BluetoothState.STATE_ON:
          this.bluetoothStateStr = '蓝牙状态：STATE_ON'
          break
        case access.BluetoothState.STATE_TURNING_OFF:
          this.bluetoothStateStr = '蓝牙状态：STATE_TURNING_OFF'
          break
        case access.BluetoothState.STATE_OFF:
          this.bluetoothStateStr = '蓝牙状态：STATE_OFF'
          break
        case access.BluetoothState.STATE_BLE_ON:
          this.bluetoothStateStr = '蓝牙状态：STATE_BLE_ON'
          break
        case access.BluetoothState.STATE_BLE_TURNING_ON:
          this.bluetoothStateStr = '蓝牙状态：STATE_BLE_TURNING_ON'
          break
        case access.BluetoothState.STATE_BLE_TURNING_OFF:
          this.bluetoothStateStr = '蓝牙状态：STATE_BLE_TURNING_OFF'
          break

      }
    })

    PermissionUtils.getInstance().checkPermissions(['ohos.permission.ACCESS_BLUETOOTH'], (isAllGrant: boolean) => {
      if (isAllGrant) {
        this.bluetoothState = access.getState()
      }
    })
  }

  aboutToDisappear(): void {
    access.off("stateChange")
  }

  build() {
    Column({ space: 10 }) {
      Text(this.bluetoothStateStr).fontColor(Color.Red).fontSize(18)
      Button('获取蓝牙权限').onClick(() => {
        this.checkBluetoothPermission()
      })
      Button(`${this.bluetoothStateStr}`)
        .onClick(() => {
          if (this.bluetoothState === access.BluetoothState.STATE_OFF) {
            access.enableBluetooth()
          } else {
            access.disableBluetooth()
          }
        })
      Button('订阅扫描结果')
        .onClick(() => {
          this.onScanBluetoothResult()
        })
      Button('开始扫描')
        .onClick(() => {
          this.startBluetoothScan()
        })
      Button('停止扫描')
        .onClick(() => {
          this.stopBluetoothScan()
        })
      List({ scroller: this.listScroller, space: 10 }) {
        ForEach(this.bluetoothDeviceList, (value: string) => {
          ListItem() {
            Text(value).fontSize(15)
          }
        }, (item: string) => item)
      }.width('100%')
      .layoutWeight(1)
    }.width('100%')

  }

  checkBluetoothPermission() {
    PermissionUtils.getInstance()
      .checkPermissions(['ohos.permission.ACCESS_BLUETOOTH'],
        (isAllGrant: boolean, deniedPermissions: Array<Permissions>) => {
          if (isAllGrant) {
            ToastUtils.show('蓝牙权限已获取')
            this.bluetoothState = access.getState()
          } else {
            this.requestPermission()
          }
        })
  }

  requestPermission() {
    PermissionUtils.getInstance()
      .reqPermissionFromUser(this.context, 'ohos.permission.ACCESS_BLUETOOTH', (isAllGrant: boolean) => {
        if (isAllGrant) {
          ToastUtils.show('蓝牙权限已获取')
          this.bluetoothState = access.getState()
        } else {
          PermissionUtils.getInstance()
            .openPermissionsInSystemSettings(this.context, this.context.abilityInfo.bundleName)
        }
      })
  }

  onScanBluetoothResult() {
    ble.on("BLEDeviceFind", (data: Array<ble.ScanResult>) => {
      if (data.length > 0) {
        for (let i = 0; i < data.length; i++) {
          let s = data[i].deviceName + '\n' + data[i].deviceId
          this.bluetoothDeviceList.push(s)
        }
        this.parseScanResult(data[0].data)
      } else {
        ToastUtils.show('未扫描到结果')
      }
    })
  }

  startBluetoothScan() {
    let scanOptions: ble.ScanOptions = {
      interval: 0, //扫描结果上报延时时间
      dutyMode: ble.ScanDuty.SCAN_MODE_LOW_POWER, //扫描模式
      matchMode: ble.MatchMode.MATCH_MODE_AGGRESSIVE, //硬件的过滤匹配模式
      // phyType:ble.PhyType.PHY_LE_1M,//扫描中使用的PHY类型
    }
    ble.startBLEScan(null, scanOptions)
  }

  stopBluetoothScan() {
    try {
      ble.off('BLEDeviceFind', (data: Array<ble.ScanResult>) => { // 取消订阅扫描结果

      });
      ble.stopBLEScan();
    } catch (err) {
    }
  }

  private parseScanResult(data: ArrayBuffer) {
    let advData = new Uint8Array(data);
    if (advData.byteLength == 0) {
      return;
    }

    let advFlags: number = -1;
    let txPowerLevel: number = -1;
    let localName: string = "";
    let serviceUuids: string[] = [];
    let serviceSolicitationUuids: string[] = [];
    let serviceDatas: Record<string, Uint8Array> = {};
    let manufactureSpecificDatas: Record<number, Uint8Array> = {};

    let curPos = 0;
    while (curPos < advData.byteLength) {
      let length = advData[curPos++];
      if (length == 0) {
        break;
      }
      let advDataLength = length - 1;
      let advDataType = advData[curPos++];
      switch (advDataType) {
        case BLE_ADV_TYPE_FLAG:
          advFlags = advData[curPos];
          break;
        case BLE_ADV_TYPE_LOCAL_NAME_SHORT:
        case BLE_ADV_TYPE_LOCAL_NAME_COMPLETE:
          localName = advData.slice(curPos, curPos + advDataLength).toString();
          break;
        case BLE_ADV_TYPE_TX_POWER_LEVEL:
          txPowerLevel = advData[curPos];
          break;
        case BLE_ADV_TYPE_16_BIT_SERVICE_UUIDS_INCOMPLETE:
        case BLE_ADV_TYPE_16_BIT_SERVICE_UUIDS_COMPLETE:
          this.parseServiceUuid(BLUETOOTH_UUID_16_BIT_LENGTH, curPos, advDataLength, advData, serviceUuids);
          break;
        case BLE_ADV_TYPE_32_BIT_SERVICE_UUIDS_INCOMPLETE:
        case BLE_ADV_TYPE_32_BIT_SERVICE_UUIDS_COMPLETE:
          this.parseServiceUuid(BLUETOOTH_UUID_32_BIT_LENGTH, curPos, advDataLength, advData, serviceUuids);
          break;
        case BLE_ADV_TYPE_128_BIT_SERVICE_UUIDS_INCOMPLETE:
        case BLE_ADV_TYPE_128_BIT_SERVICE_UUIDS_COMPLETE:
          this.parseServiceUuid(BLUETOOTH_UUID_128_BIT_LENGTH, curPos, advDataLength, advData, serviceUuids);
          break;
        case BLE_ADV_TYPE_16_BIT_SERVICE_SOLICITATION_UUIDS:
          this.parseServiceSolicitationUuid(BLUETOOTH_UUID_16_BIT_LENGTH, curPos, advDataLength,
            advData, serviceSolicitationUuids);
          break;
        case BLE_ADV_TYPE_32_BIT_SERVICE_SOLICITATION_UUIDS:
          this.parseServiceSolicitationUuid(BLUETOOTH_UUID_32_BIT_LENGTH, curPos, advDataLength,
            advData, serviceSolicitationUuids);
          break;
        case BLE_ADV_TYPE_128_BIT_SERVICE_SOLICITATION_UUIDS:
          this.parseServiceSolicitationUuid(BLUETOOTH_UUID_128_BIT_LENGTH, curPos, advDataLength,
            advData, serviceSolicitationUuids);
          break;
        case BLE_ADV_TYPE_16_BIT_SERVICE_DATA:
          this.parseServiceData(BLUETOOTH_UUID_16_BIT_LENGTH, curPos, advDataLength, advData, serviceDatas);
          break;
        case BLE_ADV_TYPE_32_BIT_SERVICE_DATA:
          this.parseServiceData(BLUETOOTH_UUID_32_BIT_LENGTH, curPos, advDataLength, advData, serviceDatas);
          break;
        case BLE_ADV_TYPE_128_BIT_SERVICE_DATA:
          this.parseServiceData(BLUETOOTH_UUID_128_BIT_LENGTH, curPos, advDataLength, advData, serviceDatas);
          break;
        case BLE_ADV_TYPE_MANUFACTURER_SPECIFIC_DATA:
          this.parseManufactureData(curPos, advDataLength, advData, manufactureSpecificDatas);
          break;
        default:
          break;
      }
      curPos += advDataLength;
    }
  }

  private parseServiceUuid(uuidLength: number, curPos: number, advDataLength: number,
    advData: Uint8Array, serviceUuids: string[]) {
    while (advDataLength > 0) {
      let tmpData: Uint8Array = advData.slice(curPos, curPos + uuidLength);
      serviceUuids.push(this.getUuidFromUint8Array(uuidLength, tmpData));
      advDataLength -= uuidLength;
      curPos += uuidLength;
    }
  }

  private parseServiceSolicitationUuid(uuidLength: number, curPos: number, advDataLength: number,
    advData: Uint8Array, serviceSolicitationUuids: string[]) {
    while (advDataLength > 0) {
      let tmpData: Uint8Array = advData.slice(curPos, curPos + uuidLength);
      serviceSolicitationUuids.push(this.getUuidFromUint8Array(uuidLength, tmpData));
      advDataLength -= uuidLength;
      curPos += uuidLength;
    }
  }

  private getUuidFromUint8Array(uuidLength: number, uuidData: Uint8Array): string {
    let uuid = "";
    let temp: string = "";
    for (let i = uuidLength - 1; i > -1; i--) {
      temp += uuidData[i].toString(16).padStart(2, "0");
    }
    switch (uuidLength) {
      case BLUETOOTH_UUID_16_BIT_LENGTH:
        uuid = `0000${temp}-0000-1000-8000-00805F9B34FB`;
        break;
      case BLUETOOTH_UUID_32_BIT_LENGTH:
        uuid = `${temp}-0000-1000-8000-00805F9B34FB`;
        break;
      case BLUETOOTH_UUID_128_BIT_LENGTH:
        uuid = `${temp.substring(0, 8)}-${temp.substring(8, 12)}-${temp.substring(12, 16)}-${temp.substring(16,
          20)}-${temp.substring(20, 32)}`;
        break;
      default:
        break;
    }
    return uuid;
  }

  private parseServiceData(uuidLength: number, curPos: number, advDataLength: number,
    advData: Uint8Array, serviceDatas: Record<string, Uint8Array>) {
    let tmpUuid: Uint8Array = advData.slice(curPos, curPos + uuidLength);
    let tmpValue: Uint8Array = advData.slice(curPos + uuidLength, curPos + advDataLength);
    serviceDatas[tmpUuid.toString()] = tmpValue;
  }

  private parseManufactureData(curPos: number, advDataLength: number,
    advData: Uint8Array, manufactureSpecificDatas: Record<number, Uint8Array>) {
    let manufactureId: number = (advData[curPos + 1] << 8) + advData[curPos];
    let tmpValue: Uint8Array = advData.slice(curPos + BLUETOOTH_MANUFACTURE_ID_LENGTH, curPos + advDataLength);
    manufactureSpecificDatas[manufactureId] = tmpValue;
  }
}